### ISSUE TITLE
GPL not a suitable choice for pictures, data files, and texts

### ISSUE THREAD

**Issue by platipodium** [rchartra/NcCut#10]
This is part of my review at https://github.com/openjournals/joss-reviews/issues/7185

While GPL is a popular open source license for source code, it does not apply well to text, pictures and data, and you have a lot of those in your repository.

- The JOSS paper.md, for example, will be released under a Creative Commons license. 
- Choose a license for texts
- Choose a license for pictures and data 
- Consider releasing all your files that have no important IP in the public domain, such as CC0-1.0. (which is applicable to software, text + data).

**Comment by rchartra** [comment]
I am under no restrictions regarding licenses. If I switch my license over to CC0-1.0 will that cover everything?

**Comment by platipodium** [comment]
> I am under no restrictions regarding licenses. If I switch my license over to CC0-1.0 will that cover everything?

Yes it would.  But I personally would do this (CC0-1.0) only for 

* data and text without much creative input from your side
* code fragments like __init__.py pyproject.toml .gititnore Makefile and similar that have no or negligible creative input from your side

For everything that is the result of your creative process, choose a different open source license.  Have a look at [choosealicense.com](https://choosealicense.com) and make a wise choice.  

Since many of your files will now have a different license, you now cannot have only one license in your LICENSE.md file, but you may have to add some license management.  I can recommend https://reuse.software
