### ISSUE TITLE
Clarify copyright to your work

### ISSUE THREAD

**Issue by platipodium** [rchartra/NcCut#12]
There is no copyright statement anywhere.  Please supply this.   I noticed that you're working for the School of Oceanography, University of Washington.  

If this work has been (partly) done as part of your job for UW, then UW holds the (partial) copyright, and ultimately decides on the license terms. If that is the case, check whether they have a policy of copyright transfer to their employees (I would doubt that) or an institutional license policy.

**Comment by platipodium** [comment]
You may want to clarify the copyright before tackling #9  #10 #11

**Comment by rchartra** [comment]
I see, I'll look into it
