### ISSUE TITLE
App unresponsive on Quit()

### ISSUE THREAD

**Issue by platipodium** [rchartra/NcCut#15]
This is part of https://github.com/openjournals/joss-reviews/issues/7185

The app is quite slow on loading, takes about 2-3 seconds on my M1 laptop.  But worse is that, when I click the Quit button, the windows is not closed but remains as a Zombie process.

**Comment by platipodium** [comment]
Also hitting the OS system's red button does not close the app.

**Comment by rchartra** [comment]
First, from some of your other issues it appears you are using an outdated version of NcCut. Could you update your version to 0.4.4 and let me know if you're still having problems? I suspect however that some of these issues will persist so I'll investigate this.

**Comment by platipodium** [comment]
This is fixed in 0.4.5.  App loading with 2 seconds is still a small wait and may annoy users.
