### ISSUE TITLE
Add unit to colorbar

### ISSUE THREAD

**Issue by platipodium** [rchartra/NcCut#19]
If a colorbar is shown with values, it should also display the variable's 'units' attribute

**Comment by rchartra** [comment]
This has been added in version 0.4.4 of NcCut

**Comment by platipodium** [comment]
Mentioning https://github.com/openjournals/joss-reviews/issues/7185

**Comment by platipodium** [comment]
I'd prefer the unit next to the colorbar but I see that this is now present.
