### ISSUE TITLE
 Error on file chooser: ModuleNotFoundError: No module named 'pyobjus'

### ISSUE THREAD

**Issue by platipodium** [rchartra/NcCut#21]
Related: https://github.com/openjournals/joss-reviews/issues/7185

I installed via conda/pip/poetry, it seems that the pyobjus dependency is not resolved correctly, though it is present in pyproject.toml

I can install it later with `pip install pyobjus` 

* resolve dependencies correctly
* please add an automated test for this issue

**Comment by rchartra** [comment]
This has been fixed (including tests) in v0.4.6
