### ISSUE TITLE
Transect Marker: symbology is difficult to visually parse

### ISSUE THREAD

**Issue by Huite** [rchartra/NcCut#39]
Related to: https://github.com/openjournals/joss-reviews/issues/7185

See this somewhat contrived example:

![image](https://github.com/user-attachments/assets/61c92b1b-92fe-415a-9644-5aa09788a9f8)

If I pay attention, I can deduce the orthogonal transects... but wouldn't this be easier?

![image](https://github.com/user-attachments/assets/3813a691-5cdb-438a-bf10-090a943acb46)

I think the optimal solution would be to make the chain dashed, and the orthogonal transects solid. This makes it consistent with the Transect Chain symbology, where the transects that are plotted are also solid.

**Comment by rchartra** [comment]
This is a good point and I like this idea. I'll implement the solid lines for the orthogonal transects and the dashed lines between the clicked points. Kivy shockingly does not have a way to make dashed lines if the width of the line is greater than one, so I need to be a little creative to make this to work.

**Comment by rchartra** [comment]
Changed it to dashed lines between clicked points and solid lines for the transects themselves.
